### PR TITLE
06/12/2021

### PR DESCRIPTION
**Pull request by tobst96**
Change Ambulance and JSON Format for quicker edit.
Add to Links "Personal" for firefighter.
Drehleiter or Teleskopmast
Add  missing Vehicles

### CODE REVIEW

**Comment by jackbayliss** [comment]
Can you re fork from master so I don't need to review so many files 😀😀

**Comment by tobst96** [comment]
There are problems?

**Comment by jackbayliss** [comment]
@aurochsen any issues?

**Comment by aurochsen** [comment]
@tobst96 the missions need to be in one line. The reason for this is uniformity of the code. The typical user doesn't and shouldn't be editing the missions files. If you want to convert all regions to the pretty json format then that is something we can discuss but right now it is not a priority.

**Comment by tobst96** [comment]
Too bad. It's been a hell of a lot of work now. Some of them have already been taken over in the project.
Otherwise I would like to take over DE completely. Since these players now ask me about mistakes or requests.
When the files are refreshed by the bot, they are again in one line. It's just nicer to work on quickly in bulk. Feel free to write to me about Discord.

**Pull request closed without merging**
