### PR TITLE
New de_DE THW Update :)

### PR DESCRIPTION
**Pull request by Suchty112**

### CODE REVIEW

**Comment by jackbayliss** [comment]
@Suchty112  ready to merge?

**Comment by Suchty112** [comment]
this. yea. another pr needs refetch from the german missions ^^

**Comment by Suchty112** [comment]
this. yea. another pr needs refetch from the german missions ^^ @jackbayliss

**Comment by Suchty112** [comment]
So LGTM @jackbayliss ;) is hopefully all right xD

**Review by jackbayliss — APPROVED** [review]
Fingers crossed :)

**Pull request merged**
