### PR TITLE
DE Mission, Link & Missing

### PR DESCRIPTION
**Pull request by tobst96**
Change Ambulance and JSON Format for quicker edit.
Add to Links "Personal" for firefighter.
Drehleiter or Teleskopmast
Add missing Vehicles
Change to one Line.
All changes are discussed with the German community.

### CODE REVIEW

**Review by jackbayliss — APPROVED** [review]
- [x] Seems good to me

**Comment by tobst96** [comment]
I'm done now. Now the player is waiting for feedback.

**Comment by jackbayliss** [comment]
@tobst96  Are they working? 👍🏻

**Comment by tobst96** [comment]
@jackbayliss Works because the mission no longer have umlauts. Everything now ?UTF-8?.

**Comment by jackbayliss** [comment]
@tobst96  I'll accept it, looks good to me, if it breaks something you'll have to fix it 🗡️

**Comment by tobst96** [comment]
@jackbayliss That's not a problem :) I'll do it for that. That just one person does it and not everyone has to touch the JSONs themselves.

**Pull request merged**
